name: Build and Push Docker Image

on:
  push:
    branches:
      - master

jobs:
  docker:
    runs-on: ubuntu-latest
    environment: DOCKER_ENV

    steps:
      # 1. Checkout the repo
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Set up Docker
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 3. Build the Docker image
      - name: Build Docker image
        run: |
          docker build -t chansy/myapp:latest .
          docker tag chansy/myapp:latest chansy/myapp:${{ github.sha }}

      # 4. Push both tags to Docker Hub
      - name: Push Docker image
        run: |
          docker push chansy/myapp:latest
          docker push chansy/myapp:${{ github.sha }}
  deploy_vps: 
    runs-on: ubuntu-latest
    needs: docker
    environment: VPS_ENV
    
    steps:
    - name: SSH and Deploy
      uses: appleboy/ssh-action@v0.1.7
      with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
                # Pull the new Docker image
                docker pull chansy/myapp:${{ github.sha }}
                # Stop and remove the existing container
                docker stop myapp || true
                docker rm myapp || true
                # Run the new container
                docker run -d --name myapp -p 3000:3000 chansy/myapp:${{ github.sha }}
